### ISSUE TITLE
test_k_matrix_ChannelSubset_iasi_metop-b (SEGFAULT)

### ISSUE THREAD

**Issue by chengdang** [JCSDA/CRTMv3#80]
This ctest is puzzling. 

It passed with dev branch last week.
After PR [#75](https://github.com/JCSDA/CRTMv3/pull/76), it fails now.
With branch [feature/cd_RTSout_netCDF](https://github.com/JCSDA/CRTMv3/tree/feature/cd_RTSout_netCDF), PR https://github.com/JCSDA/CRTMv3/pull/66, it also fails.

I don't see any obvious changes in PR #75 PR #66 that would have caused the failing of this test.

**Comment by chengdang** [comment]
With the most recent test on PR #79, both `ChannelSubset_iasi-metop-b tests` failed:

```
The following tests FAILED:
	 34 - test_forward_ChannelSubset_iasi_metop-b (Failed)
	 90 - test_k_matrix_ChannelSubset_iasi_metop-b (Failed)
Errors while running CTest (edited)
```

They both passed with Fabio's test

**Comment by BenjaminTJohnson** [comment]
After investigation, it turns out that the way that the logic that chunks the channels doesn't quite work correctly for subsetted channels.   There's an offset by 1 somewhere, resulting in "Channel 0" being output in the inspection routines.    Continuing to work on this in branch: `feature/btj_openMP_over_ch_fix`
